
tasks:
  - name: Packages
    before: |
      sudo install-packages mc dos2unix
      python3 -m pip install -U --user ipython numpy pandas rich
    command: | 
      export TZ='Europe/Berlin'

vscode:
  extensions:
    - ms-python.python
    - esbenp.prettier-vscode
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-toolsai.vscode-jupyter-slideshow
    - streetsidesoftware.code-spell-checker
