
tasks:
  - name: Packages
    init: |
      sudo install-packages mc dos2unix 
      python3 -m pip install -U --user ipython numpy pandas rich    
    command: |
      echo "OK"

vscode:
  extensions:
    - ms-python.python
    - esbenp.prettier-vscode
