
tasks:
  - name: Packages
    command: |
      sudo install-packages mc dos2unix
      python3 -m pip install -U --user ipython numpy pandas rich
      pyenv rehash  
      export TZ='Europe/Berlin'

vscode:
  extensions:
    - ms-python.python
    - esbenp.prettier-vscode
    - ms-toolsai.jupyter
